# Please run all npm installs using the included Makefile
# bash command => `make install`
version: '3'
services:
    dev:
        image: node:14.14.0-buster
        volumes:
            - .:/usr/src/app
        working_dir: /usr/src/app
        command: npm run serve
        ports:
            - 3000:3000 #express
            - 3030:3030 #express api
            - 5000:5000 #svelte
            - 35729:35729 #livereload
        depends_on:
            - mongo
    mongo:
        image: mongo
        ports:
            - 27018:27017 #exposed at 27018 in case mongo is installed locally
        volumes:
            - data-volume:/data/db
volumes:
    data-volume: